name: ci-cd

on: 
  push: 
    branches: 
      - 'main' 
    pull-request: 
      branches:
        - 'main'

jobs:
  cd:
    runs-on: ubuntu-latest 

    steps: 
      - name: cicd
      run: echo "todoApp"